name: Generate and Commit Migrations

on:
  push:
    branches:
      - main  # 监听 main 分支的变更

jobs:
  generate-migrations:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # 使用适合项目的 Python 版本

    # 3. 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. 切换到 main-migrations 分支
    - name: Switch to migrations branch
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config pull.rebase false  # 设置合并策略为 merge
        
        # 获取所有远程分支信息
        git fetch origin main-migrations
        
        # 检查远程分支是否存在，如果不存在则从当前分支创建
        if git ls-remote --heads origin main-migrations | grep main-migrations; then
          git checkout -b main-migrations origin/main-migrations
        else
          git checkout -b main-migrations
          git push -u origin main-migrations
        fi
        
        git pull origin main --no-rebase --allow-unrelated-histories || true

    # 5. 生成迁移文件
    - name: Generate migrations
      run: |
        python manage.py makemigrations
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        # 使用 -f 强制添加被忽略的迁移文件
        git add -f */migrations/*.py

    # 6. 提交并推送迁移文件
    - name: Commit and push migrations
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add -f */migrations/*.py
        git commit -m "Auto-generated migrations [skip ci]" || git commit -m "No changes in migrations [skip ci]" --allow-empty
        git push -f origin main-migrations
